name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  

      - name: Terraform Init
        working-directory: ./infrastructuress
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infrastructuress
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./infrastructuress
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        working-directory: ./infrastructuress
        run: terraform destroy -auto-approve tfplan
